### ISSUE TITLE
Should we use cloudquery ?

### ISSUE THREAD

**Issue by da-ekchajzer** [Boavizta/cloud-scanner#2]
Should we use cloud query : https://www.cloudquery.io/ ?

**Comment by demeringo** [comment]
Very valid question ! 

I am a bit undecided yet:
- on the pro side, cloud query seems to provide a ton of features, and its active development let me think that it already supports (or will soon) a lot of aws (and other) cloud resources.
- but on the negative side, it seems relatively heavy (needs its own database) and in my understanding it requests a installation or configuration step.

My vision on this (but it is open to discussion !) is that I would like to _try_ gathering usage metrics using the simpe aws API/SDK first. And if it turns out to be too difficult this way (or require too much custom code) try to integrate some higher level  tool like _cloud query_.

IMHO, One of the drivers for the design of cloud scanner is that it should be a near zero installation process (hence the production of a Rust binary that makes it easy to just download and execute).

I have also in mind another way to use the scanner in larger Enterprise context (where end user may not have direct access to the AWS credentials),  by deploying the scanner as a lamdba or small serverless app. 

So I would rather keep the scanner it as light as possible in term of dependencies (except Boavizta API and AWS sdk).

**Comment by da-ekchajzer** [comment]
I am pretty convince by doing a very lite application easy to use, easy to deploy. Just wondering if it will be easy to make it work for Azure or GCP ?

Maybe a use case using cloud query would be a cloud query plugin for organizations which already have set up the tool. But it's another story ;).
