### ISSUE TITLE
Compilation error : failed to run custom build command for 'ring v0.16.20'

### ISSUE THREAD

**Issue by albanducos87** [Boavizta/cloud-scanner#78]
Hello everyone
I hava an issue when I want to execute this command : `serverless deploy`

My terminal show me an error and after many and many attempts, I don't know what to do.

Here's the error : 
![image](https://user-images.githubusercontent.com/48727004/181735512-334f1bcc-20b8-4883-9528-caed77ea75dd.png)

**Comment by demeringo** [comment]
Hello @albanducos87, thank you for openning the issue.

I did not test (yet) the compilation or serverless deployment from Windows, as I do all the development from Linux.

But I suspect that the error is related to cross-compiling (from a windows machine to produce a binary suitable for lambda deployment). Something may be need to be installed for the cross compilation to work from Windows.

I really do not have much experience with such setup, but solution may be related to something like:
- https://github.com/briansmith/ring/blob/main/BUILDING.md#supported-toolchains
- https://users.rust-lang.org/t/how-to-cross-compile-linux-binaries-with-rust-from-windows-hosts/15218/4
- https://github.com/japaric/rust-cross/issues/33#issuecomment-373524388

**Posssible workaround**:

If setting up a Rust + serverless environment on Windows is too much complication, a simpler workaroound could be either to 
- run the commands from WSL (The Windows Subsystem for Linux)
or
- use a temporary AWS or Azure Linux instance (Ubuntu or Debian) and use it to checkout / compile / deploy the lambdas.

Sadly, I may not be able to give you much support in the coming days, because I'm traveling and do not have a Windows laptop with me to do the tests.

**Comment by jfaixo** [comment]
Hi,

I reproduced the problem. This is a problem related to cross compilation of the ring crate while targetting linux-musl (the target that is set in serverless) from windows.

See for example:  briansmith/ring/#1472

The workaround seems to be to use WSL when you want to cross-compile...

**Comment by demeringo** [comment]
Thanks @jfaixo, I realize that I used the `dockerless=true` setting in the serverless.yml file: https://github.com/Boavizta/cloud-scanner/blob/5ace291ce41216ca009ff9eba856043845e44260/serverless.yml#L26

According to serverless-rust plugin doc, it means that I had to add the `x86_64-unknown-linux-musl` target https://github.com/softprops/serverless-rust#-experimental-local-builds. 

I probably did this initially with the following command: `x86_64-unknown-linux-musl`

**Comment by jfaixo** [comment]
Rust is usually very good at cross compilation, but the ring crate embeds C code I think, which require to have a fully blown toolchain for compiling C for the target platform, so it's becoming way more complex.. containerizing is the way !

**Comment by demeringo** [comment]
Long story short,: 
1. we need to install musl development packages in Linux.
2. add x86_64-unknown-linux-musl as a target for the Rust compiler .

## 1. Check availability and install if needed musl
```sh
#  Warning: musl-gcc may be missing, wich results in error: 
#    error: failed to run custom build command for `ring v0.16.20`
# it can be verified by trying to call musl-gcc on command prompt
# $ musl-gcc
# Which results in:
#    Command 'musl-gcc' not found, but can be installed with:
# This musl-gcc is not available (preventing cross compilation)

# On linux  Need to install musl-gcc
sudo apt update && sudo apt install -y musl-tools musl-dev
```
## 2. Install x86_64-unknown-linux-musl as rustup target

```sh
# Add Linux musl target (needed for cross compilation for aws lambda)
rustup target add x86_64-unknown-linux-musl
```

**Comment by demeringo** [comment]
Not yet mentionned in the docs but I published a docker image to use Rust + Serverless in CI:
https://github.com/demeringo/rust-serverless-ci

```sh
# get image
docker pull ghcr.io/demeringo/rust-serverless-ci:latest
```
